### ISSUE TITLE
Is WebSocket4Net compatible with Unity3D?

### ISSUE THREAD

**Issue by floatinghotpot** [kerryjiang/WebSocket4Net#92]
When I attempt to use your WebSocket4Net in Unity3D, it reports that the assembly could not be loaded.

As we know, in most cases, mono 2.x (.NET 2.0 / .NET 2.0 subnet) is used as Unity3D script backend. 

Is WebSocket4Net compatible with Unity3D? 

If Yes, it will be great, as Unity game developers can use it. It's a very massive need.

**Comment by kerryjiang** [comment]
Yes, some developers already use it in Unity3D applications.

**Comment by floatinghotpot** [comment]
Thanks for the quick response, I've now tested it in Unity3D, and it does work well. Thanks.

**Comment by farukcan** [comment]
When I implement that to unity i getting error like : 
> The imported type `System.Func<T,TResult>' is defined multiple times

how i fix that?

**Comment by Lesliehdezg** [comment]
me too, i have the same error: 
error CS0433: The imported type `System.Action<T1,T2>' is defined multiple times

**Comment by dill0wn** [comment]
Yeah, I'm seeing the same thing :(

**Comment by OptrixAU** [comment]
I resolved it by removing the Unity Package Manager (which actually required deleting the files from the Unity installation, since you can't normally remove the package manager any other way).

Both the package manager and WebSocket4Net define System.Func to emulate a higher version of the .NET standard. Unfortunately, this means they conflict.

**Comment by hoangphamemotiv** [comment]
@floatinghotpot can you tell more detail how make WebSocket4Net  work with Unity?
